### ISSUE TITLE
Comparar as likelihoods

### ISSUE THREAD

**Issue by j-faria** [jdavidrcamacho/Tests_GP#1]
Sugeria que tentássemos trabalhar aqui no github, usando os issues :)
Consegues adicionar ao ficheiro `log_likeli.py` o cálculo da likelihood com o George, usando os kernels do George também? 
Assim era mais fácil comparar tanto a likelihood como os valores intermédios para perceber o que pode estar diferente.

**Comment by jdavidrcamacho** [comment]
Eu coloquei um ficheiro python comparacao_likelihood.py onde é só correr e devolve a likelihood calculada pelo george e a calculada pelo programa feito por mim para um exemplo.

A  minha duvida é uma que no fundo até deve ser simples. 
Se veres o código, logo ao inicio na parte dos dados tens  um termo que é o yerr (linha 18),  e que ao ir pesquisando sobre como calcular a likelihood pelo que encontrei é adicionado aos elementos da diagonal da matriz de covariancia (faço isso na linha 54).
A duvida que me surgiu é que quando temos uma kernel em que  nela também temos um termo para o white noise, o delta de kronecker vai implicar que o white noise só influencia os valores da diagonal da matriz de covariancia certo? 
Entao o yerr, que eu pensava que era o erro da medição dos yy, é no fundo uma espécie de white noise ou nao tem nada a ver uma coisa com a outra?

**Comment by j-faria** [comment]
Pois, o erro estava mesmo no `yerr`. 
Quando tens um kernel de white noise tens só um parametro, seja s. Normalmente adicionas à diagonal da matriz de covariância s^2. Este é o mesmo valor para todos os pontos.
O `yerr` entra também só na diagonal, também ao quadrado mas pode ser diferente de ponto para ponto.
Ou seja,

Kij = s * delta_ij + sigma_i * delta_ij + outros termos do kernel

Mas basicamente o único erro que tinhas era
`K=K+yerr*np.identity(len(x))`
onde devias ter
`K=K+yerr**2*np.identity(len(x)) `

**Comment by jdavidrcamacho** [comment]
Andei a fazer testes com outras kernels e  os resultados que obtive até agora para a likelihood estao no ficheiro 02_likelihood_testes.py

Agora surgiu-me uma questão importante! Eu tenho as kernels que uso no ficheiro kernel.py e calcular a likelihood funciona se estiver apenas a trabalhar com uma kernel, agora se eu quiser por exemplo somar duas kernels e calcular a likelihood a coisa complica pois sempre que o quiser fazer a opção que encontrei foi ir ao ficheiro  kernel.py e criar uma nova kernel onde incluo a soma. 

Tens alguma sugestão de uma maneira mais eficaz para somar kernels? É que se por exemplo eu quiser testar a soma de 8, depois 9, depois 10 kernels diferentes, acaba por se muito pouco eficiente estar sempre a ir ao ficheiro kernel.py e criar uma nova kernel para cada uma das somas.

**Comment by j-faria** [comment]
Vê o pull request que fiz agora em relação ao cálculo da likelihood.

Para juntar os kernels o melhor é fazeres como no george e criares classes. Depois fazes o que se chama "overload" dos operadores de adição e multiplicação. Só tens que definir as funções `__add__` e `__mul__` Vê [aqui](https://github.com/dfm/george/blob/master/george/kernels.py).

**Comment by jdavidrcamacho** [comment]
Tentei usar classes para somar e mutiplicar kernel (04_SumMultiplication.py) mas nao funciona bem, para somar parece resultar, multiplicar nao resulta.

Como não conseguia avançar usando classes tentei usando o que ja tinha feito antes e ai consegui, os ficheiro estão numa nova pasta New_Attempt. No ficheiro likelihood_testes.py consigo calcular a likelihood de uma kernel só, da soma de duas kernels e da multiplicação de duas kernels, creio que para mais kernel tambem irá funcionar e vou passar o resto do dia a testar a ver se não há problema. O único pormenor é que a maneira que é  feita não utiliza classes, se detectares algum erro que me tenha passado despercebido por favor avisa!  :)

**Comment by jdavidrcamacho** [comment]
Tive a fazer testes e o calculo da likelihood da pasta New_Attempt não funciona mas vou passar a manhã a ver o que está mal e tentar corrigir, depois dou noticias.

**Comment by jdavidrcamacho** [comment]
O calculo da likelihood da pasta New_Attempt já funciona mas voltei ao problema anterior, somar ou multiplicar nao funciona x)
Vou voltar a rever o que andei a fazer com classes e tentar aplicar ao que fiz nessa pasta

**Comment by jdavidrcamacho** [comment]
Quando puderes dá uma vista  de olhos aos ficheiros que estão na pasta New_Attempt a ver o que ando a fazer de mal, lá contém um ficheiro readme a explicar as coisas.

**Comment by jdavidrcamacho** [comment]
Boas!

Acho que finalmente descobri o que andava mal na soma de kernels!
Pelo que me deu a parecer não tem tem a ver com erros no código do python mas sim com os parâmetros que inserimos nas nossas kernels e nas do george, por exemplo:

Olhando À soma de uma kernel nossa temos

`k1 = kl.ExpSquared(2.0,1.0) + kl.ExpSineSquared(3.0,5.0,1.0)`

Na kernel ExpSineSquared(theta,l,P) theta é a amplitude, l um parâmetro que sinceramente ainda não percebi bem o que é, e P é o período.

No george a mesma soma tem de ser dada como

`k2 = 2.0**2*ExpSquaredKernel(1.0**2) + 3.0**2*ExpSine2Kernel(2.0/5.0**2,1.0)`

Onde na kernel ExpSine2Kernel a amplitude passa para fora da função ao quadrado, e o que dá-mos à função é 2/(l**2) e o período.
Eles definem o parâmetro l de maneira diferente daquela que usei.
Eu fui ao livro "Gaussian Processes for Machine Learning" do Rasmussen e Williams para ver as kernels e construí-as a partir de lá.

Creio que olhando a este pormenor tanto a soma e a multiplicação funcionam e quando puderes dá uma vista de olhos :)

Abraço!

**Comment by jdavidrcamacho** [comment]
Andei a tentar ver como calcular o gradiente da likelihood e preciso de ajuda porque cheguei a um passo que nao sei resolver. xD

Pelo que pesquisei do calculo do gradiente  é preciso as derivadas em ordem a cada uma das  variaveis da kernel que usamos.
O meu plano era em vez que meter o python a calcular numericamente as derivadas pois isso consome memoria, tempo e tem erros associados, eu tinha o plano  de  da mesma maneira que criamos classes para as kernel, criar tambem para as suas derivadas (isso está nas linhas 153  a 271  do Kernel.py) eu acho que isto poupava memoria ao python pois não o metia a calcular derivadas mas sim só a meter os valores nas expressoes e a devolver valores.

Agora com este plano surge-me os problemas, eu criei a função variables  (linha 303)  que me devolve os valores iniciais das variaveis da kernel que estamos a usar  mas não sei como utilizar/inserir esses valores nas expressões das derivadas, outro problema que também não sei é como meter o python a associar as derivadas à kernel, isto é, a  kernel ExpSquared vai ter duas derivadas, uma em ordem a theta e outra em ordem a l, agora nao sei como dizer ao python se estamos a usar a kernel ExpSquared vai buscar as duas expressões da derivada e calcula novas matrizes de covariancia com estas derivadas.

Se o que tentei explicar aqui tiver ficado muito confuso avisa que passo ai na sala assim que puder :)

**Comment by j-faria** [comment]
Só chego ao Porto amanhã e não sei se vou ter muito tempo esta semana para olhar para isto. De qualquer maneira parece-me overkill criar novas classes, mais vale implementar uma função dentro de cada classe, por exemplo. Uma coisa que valia a pena olhar era para diferenciação automática, no estilo do [autograd](https://github.com/HIPS/autograd). 
PS: cria novos issues e fecha este ;)

**Comment by jdavidrcamacho** [comment]
Fiz um novo issue qualquer coisa que tente meto lá a dizer os resultados :)
