### ISSUE TITLE
Derivadas e gradiente

### ISSUE THREAD

**Issue by jdavidrcamacho** [jdavidrcamacho/Tests_GP#5]
@j-faria desculpa o testamento mas vou tentar explicar tudo o melhor que conseguir xD

Eu andei a ver e comparar as derivadas das kernels e calculo do gradiente da nossa maneira e da maneira como o george faz e acho que não faz sentido tentar obtermos o mesmo valor de gradiente que no george em alguns casos.
Olhando por exemplo à kernel eu chamo de ExpSineSquared (ESS para simplificar) e que no george tem o nome  de ExpSine2Kernel  (ES2  para simplificar). 
A expressão que nós temos e que eu tirei do Rasmussen&Williams é :

`ESS = theta**2 * exp( -(2/L**2) * sin(pi*(x1-x2)/P)**2)`

As variáveis que temos na nossa expressão é theta. L e P, vai ser em relação a essas que depois vamos calcular as derivadas parciais.

O george por sua vez define:

`ES2 = theta**2 * exp(-Gamma  * sin(pi*(x1-x2)/P)**2)`

As variáveis deles são theta, Gamma e P, e nos exemplos do george têm o cuidado de quando metem um valor no Gamma (por exemplo 1.3) metem-no como 2/1.3**2, como eles fazem neste exemplo [http://dan.iel.fm/george/current/user/hyper/#optimization](url). Pelo que eu percebi, e corrige-me se estou em erro, mas no fundo as expressões vão dar o mesmo resultado no calculo da likelihood (como acontece) simplesmente nas nossas kernel e nas kernels do george metemos os valores de forma diferente.

Agora as diferenças acontecem quando derivamos as funções em relação às suas variáveis. Quando pegamos na nossa kernel e derivamos por exemplo em ordem  a L (tirei os thetas nas expressoes escritas aqui ficarem mais pequenas e fáceis de perceber, eles nao influenciam os cálculos pois são iguais nos dois lados) obtemos:

`dESS/dL = (4 / L**3) * sin(pi*(x1-x2)/P)**2 * exp( -(2/L**2) * sin(pi*(x1-x2)/P)**2)`

No george observei o codigo escrito aqui [https://github.com/dfm/george/blob/master/include/kernels.h#L414](url)

Eles derivam correctamente em ordem a gamma e obtém a expressão:

`dES2/dGamma = - sin(pi*(x1-x2)/P)**2 * exp( -Gamma * sin(pi*(x1-x2)/P)**2)`

O resultado disto é que ao calcularmos o gradiente temos neste caso resultados com sinais opostos, isto é se na nossa expressão o valor para o gradiente de dESS/dL for 10, o gradiente do george dá -10, o que a meu ver faz sentido pois temos expressões das derivadas com sinais diferentes. 
A meu ver o facto de termos valores de gradientes diferentes ao george faz sentido porque as expressões são diferentes e o que interessa no fim será ao aplicarmos o algoritmo de optimização dos parâmetros no fim conseguir chegar ao mesmo resultado.

Este pormenor acontece noutras kernels também, por exemplo na Rational Quadratic temos a expressão:

`RQ = theta**2 ( 1 + (x1-x2)**2/2*alpha* L**2) ** (-alpha)`

Enquanto no george têm a expressão:

`RQ = theta**2 ( 1 + (x1-x2)**2/2*alpha* L) ** (-alpha)`

A diferença é que temos L**2 enquanto eles têm apenas L, novamente se fores a ver os exemplos por eles usados [http://dan.iel.fm/george/current/user/hyper/#optimization](url), eles têm o cuidado de inserir um valor para L ao quadrado enquanto nós não o precisamos de o fazer.
Tal como na primeira kernel as derivadas que vamos obter vão ser diferentes e vão dar valores diferentes.

Depois disto a minha conclusão é que faz sentido obtermos gradientes de valores diferentes aos do george para certas variáveis pois estão definidas de maneiras diferentes e o que vai interessar é ao aplicarmos a optimização obtermos o mesmo resultado. 
Se estiver a pensar mal  e tiver de repensar alguma coisa por favor diz, enquanto isso vou tentar ver como aplicar e calcular gradientes a somas e multiplicaçoes de kernels  para adiantar trabalho xD

Abraço e não trabalhes só também diverte-te por Itália :D

**Comment by j-faria** [comment]
Concordo plenamente, algumas variáveis são diferentes e não faz sentido esperar que as derivadas sejam iguais. De qualquer maneira para as variáveis comuns (tipo os `theta**2` ou o `P` por exemplo) podes confirmar se dá igual não? Só para ter um teste que diga que o cálculo das derivadas está correcto.

Estou a guardar-me para o fim de semana em Roma :D
Abraço!

**Comment by jdavidrcamacho** [comment]
Bem eu acho sinceramente  que tenho um erro no calculo gradiente, eu defini uma kernel exactamente igual ao george

class  ExpSineGeorge(Kernel):

    def __init__(self,gamma,P):
        super(ExpSineGeorge,self).__init__(gamma,P)
        self.gamma=gamma
        self.P=P`
        
    def __call__(self,x1,x2):
        f1=self.gamma
        f2=self.P
        f3=x1-x2
        return np.exp(-f1 *  np.sin(np.pi*f3/f2)**2)
        
    def dE_dGamma(self,x1,x2):
        f1=self.gamma
        f2=self.P
        f3=x1-x2
        f4 = -np.sin(np.pi*f3/f2)**2
        f5 = np.exp(-f1*np.sin(np.pi*f3/f2)**2)
        return f4*f5 
       
    def dE_dP(self,x1,x2):
        f1=self.gamma
        f2=self.P
        f3=x1-x2
        f4 = np.sin(np.pi*f3/f2)
        f5 = np.cos(np.pi*f3/f2)
        f6 = np.exp(-f1 *  np.sin(np.pi*f3/f2)**2)
        return 2*f1*(np.pi*f3/f2)*f4*f5*f6/f2


Tanto esta kernel como as suas derivadas estão iguais ao que é definido no george e a likelihood tal como antes dá um valor igual calculado da nossa maneira e calculado a partir do george, logo sendo isto tudo igual, o gradiente devia dar igual sem desculpas de as derivadas serem diferentes.
Não dá o python devolve isto:

`likelihood_nosso -> -223.987614734`
`gradient_nosso -> 3.18182526119 326.006189056`
`likelihood_george -> -223.987614734`
`gradient_george -> 6.36365052  1630.03094528`

Devo ter feito asneira na função onde tenho a expressao do calculo do gradiente, talvez  algures aqui:

` grad = 0.5 * np.dot(y.T,np.dot(K_inv,np.dot(K_grad,np.dot(K_inv,y)))) \
            -0.5 * np.einsum('ij,ij',K_inv,K_grad)  `

Numa expressão tao grande é possível que tenha feito algo mal,  assim  que descobrir onde acontece dou noticias :)

**Comment by jdavidrcamacho** [comment]
Olá ! Há uma coisa que eu sinceramente não estou a perceber e nao consigo encontrar o erro.

Fui ao george e tirei de lá a maneira como eles calculam o gradiente e meti no nosso codigo, 

    A = np.outer(alpha, alpha) - K_inv 
    grad_george = 0.5 * np.einsum('ij,ij', K_grad, A)
    return grad_george

O alpha = K_inv *y e vem da formula 5.9 do Rasmussen & Williams [http://www.gaussianprocess.org/gpml/chapters/RW5.pdf](url), o k_inv é a inversa da matriz de covariancia da kernel e K_grad é a matrix de covariancia da kernel derivada que estamos a usar.

Antes tinha 

    grad = 0.5 * np.dot(y.T,np.dot(K_inv,np.dot(K_grad,np.dot(K_inv,y)))) \
            -0.5 *np.trace(np.dot(K_inv,K_grad))             
    return grad

Os valores que se obtem da maneira do george e com o codigo que estava escrito antes é igual por isso creio que o problema nao está ai.

Para testar tudo e nao haver desculpas de valores diferentes por causa das variaveis nas nossas kernels e nas do george serem diferente criei uma kernel igual  ao george, neste caso:

    kernel(gamma,P) = exp(-gamma * sin(np.pi * (x1-x2) / P)**2)

E que está na linha 241 de [https://github.com/jdavidrcamacho/Tests_GP/blob/master/Programs%20made/Kernel.py#L241](url)

Criei as respectivas derivadas que pelo que me parece também são iguais às definidas no george [https://github.com/dfm/george/blob/master/include/kernels.h#L423](url)

O calculo da likelihood não me dá problema nenhum pois o valor obtido é igual no nosso programa e no george.

O calculo do gradiente dá diferente  mas observei um pormenor!
Se eu for às derivadas que eu defini, por exemplo à derivada da kernel em ordem a gamma (que vou chamar dK/dG para simplificar)
 
Inicialmente e correctamente(acho :s) a derivada é:

    dK/dG = - sin (np.pi*(x1-x2)/P)**2 * exp(-gamma * sin(np.pi * (x1-x2) / P)**2)

Corro o python e obtenho o gradiente, que claro até agora não é igual ao obtido no george.
Mas se eu voltar à derivada e no codigo multiplica-la por gamma, isto é 

    dK/dG = - sin (np.pi*(x1-x2)/P)**2 * exp(-gamma * sin(np.pi * (x1-x2) / P)**2) * gamma

Mandar o python correr obtenho o valor igual ao george!
E o mesmo acontece quando é a derivada em ordem a P. A expressão que tenho escrita não dá valor igual ao george mas se for à derivada e multiplica-la por P já obtenho o mesmo valor que o george.
Olhando às matrizes de covariancia tambem só nesse caso dão iguais ao george. Tendo as formulas das derivadas, as matrizes são diferentes, quando multiplico-as por gamma ou P as matrizes ficam iguais às do george.

Estou a pensar no calculo do gradiente de forma errada em so usar a formula 5.9 do Rasmussen e Williams?

**Comment by jdavidrcamacho** [comment]
@j-faria 

Finalmente percebi o que é preciso fazer:

df(x)/dx = df(x)/dlog(x) * dlog(x)/dx  -> Via chain rule

df(x)/dx = df(x)/dlog(x) * 1/x

Logo:

df(x)/dlog(x) = x * df(x)/dx

Demorei mas agora acho que não vai haver problemas com os cálculos xD
Abraço

**Comment by j-faria** [comment]
Óptimo! Então se fizeres todas as derivadas em ordem ao logaritmo das variáveis, depois deves fazer a minimização usando o log também.
O meu conselho agora seria:
 - fechar este issue, 
 - escrever um ou dois testes para estes cálculos que tens andado a fazer (para ter a certeza que com as modificações que fizeres no futuro isto dá sempre valores correctos)
 - tentar organizar e limpar um bocadinho o código (mas podemos falar disso mais tarde)

Nice work! :+1:

**Comment by jdavidrcamacho** [comment]
Certo, eu pensava EM agora ver e meter o gradiente de somas e multiplicaçoes a funcionar (somas parece-me funcinar, multiplicações ainda nao) e depois disso organizar o codigo.
Eu começo a reparar que ando a repetir passos e linhas de codigo em certos casos mas queria primeiro ter todos os calculos do gradiente a funcionar para depois entao ver onde posso melhorar o codigo.

Vou fechar este issue, qualquer coisa logo à tarde ando no caup e falamos
Abraço! :smiley:
