### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by jdavidrcamacho** [jdavidrcamacho/Tests_GP#7]
@j-faria 

Tenho andado a tentar implementar o gradient descent algorithm estes dias e ainda nao consegui, o george usa o scipy para optimizar os parâmetros das kernels mas eu achei que o melhor seria tentar fazer o programa do zero até porque nao percebo bem como o scipy.optimize funciona :s 

Espero conseguir a coisa a funcionar esta semana e encontrei uma coisa que me parece interessante fazer:

[http://ml.informatik.uni-freiburg.de/_media/publications/blumesann2013.pdf]

É um outro algoritmo que também serve para optimizar os parâmetros, achas que podia ser util implementa-lo depois de meter o gradient descent a funcionar? 
A lógica por detrás do rprop algorithm parece-me idêntica à do gradient descent e assim que o conseguir meter a funcionar, nao me parece que va ser muito dificil implementar este novo e sempre podia servir para comparar resultados ou algo do genero.

Depois diz o que achas abraço :smiley:

**Comment by jdavidrcamacho** [comment]
Não percebo como meter links a funcionar aqui :disappointed:
Desculpa mas acho que vais ter de fazer copy paste ao link :disappointed:

**Comment by j-faria** [comment]
Acho que não era má ideia usar o `scipy.optimize`, porque podes escolher entre vários algoritmos para testes e as implementações são standard. Mas mesmo assim não tem mal nenhum se implementares o gradient descent do zero. 
O outro algoritmo também me parece promissor, quando conseguires pô-lo a funcionar. 

Depois disso podemos pensar na implementação de um MCMC que use as derivadas, como o Hamiltonian Monte Carlo. Podes ver o [Stan](http://mc-stan.org) ou o [PyMC3](http://pymc-devs.github.io/pymc3/). 

PS: aqui não vejo o link, mas no telemovel funciona...
