### ISSUE TITLE
Nome

### ISSUE THREAD

**Issue by j-faria** [jdavidrcamacho/Tests_GP#8]
Vai pensando num nome para dar ao código! :)

**Comment by jdavidrcamacho** [comment]
Ok vou pensar em alguma coisa :D

**Comment by j-faria** [comment]
**Gedi** ? 
Depois tens que pensar num acrónimo!

![image](https://cloud.githubusercontent.com/assets/1958991/20529469/2bd44a40-b0c8-11e6-821d-26e9f018a68d.png)

**Comment by jdavidrcamacho** [comment]
Gedi - The Gaussian Jedi até me parece boa ideia xD

Tambem pensei em Gausspack só para depois por preguiça minha possa fazer no python "Import Gausspack as gp" ou algo do genero e fica despachado xD

Ah para dar um resumo do que andei a fazer, fiz três algoritmos para optimizar os parametros das kernels, o algoritmo de steepest descent que é o mais basico mas tambem nada eficiente, o conjugate gradient  method que é o que pelo que percebi é o que george usa com o scipy e fiz o RPROP daquele artigo que te falei.
Eu em nenhum dos três consigo obter tão bons resultados como o george com o scipy.optimize e se não conseguir perceber o porque creio que amanhã vou tentar aplicar o scipy e os algoritmos que eles já tem. Depois dou-te noticias ou passo ai em cima se surgir alguma coisa :D

**Comment by jdavidrcamacho** [comment]
Para dar-te um pequeno exemplo do que consigo ter, limitando os algoritmos a 20 iterações para ver o que conseguem obter:

**RPROP**
Initial kernel -> ExpSineGeorge(1.65289256198, 7.1)
Initial likelihood -> -59.715979981

total iterations -> 20
final likelihood -> 7.41907633793
final kernel -> ExpSineGeorge(2.56316182291, 11.7007173182)


**CGA**
Initial kernel -> ExpSineGeorge(1.65289256198, 7.1)
Initial likelihood -> -59.715979981

total iterations -> 20
final likelihood -> 0.674219612123
final kernel -> ExpSineGeorge(0.834801004316, 10.9468271621)


**SDA**
Initial kernel -> ExpSineGeorge(1.65289256198, 7.1)
Initial likelihood -> -59.715979981

total iterations -> 20
final likelihood -> -16.8198693474
final kernel -> ExpSineGeorge(1.29641922365, 9.3755167556)


**george**
Initial kernel -> ExpSine2Kernel(1.65289256198, 7.1)
likelihood_george -> -59.715979981

total iterations -> 20
likelihood_george -> 15.427680453
kernel_george -> ExpSine2Kernel(0.403059653034, 6.17557937538)

**Comment by j-faria** [comment]
Se gostas do nome cria um novo repositório, mesmo que vazio (com um README e LICENSE)

Em relação aos algoritmos, o `scipy.optimize.minimize` usa o BFGS por defeito. Ou seja, acho que é esse algoritmo que é usado [aqui](http://dan.iel.fm/george/current/user/hyper/#optimization). Podes tentar implementar esse também, não acho que seja muito difícil se já fizeste os outros. Assim deves conseguir os mesmos resultados. Outra coisa que podes tentar é usar os mesmos dados, que são descritos no Rasmussen e Williams. 

Outra coisa: limitar o número de iterações é igual a limitar o número de cálculos da likelihood? Ou seja, todos os métodos calculam a likelihood o mesmo número de vezes por iteração? E em termos de tempo não há diferenças?
Nenhum desses métodos é estocástico, sempre que corres dá o mesmo resultado certo?

**Comment by jdavidrcamacho** [comment]
Sim limitar as iterações vai limitar o numero de calculos de gradientes.
A ideia que tenho dos os algoritmos caminham para a solução optima de acordo com um certo "step", e no fim de cada step ele vai voltar a calcular gradientes para ver em que direcção dar o proximo step, ou seja um algoritmo vai ser melhor quanto menos steps der até a solução optima, isso vai implicar menos tempo e cálculos gastos. Ao limitar a 20 iterações por exemplo, conseguimos perceber qual dos algoritmos chegou "mais perto" da solução optima, o calculo final da likelihood vai comparar-te os modelos (quando mais alto melhor) e assim ves qual deles foi.
Por exemplo no que te  mostrei acima, mais perto da solução optima foi o george (likelihood=15.4),  depois o RPROP (likelihood=7.4),  depois o CGA (likelihood=0.67)  e no fim o SDA, como esperado, com likelihood= -16.8. Pelo menos esta é a ideia que tenho se estiver mal por favor diz xD

**Comment by jdavidrcamacho** [comment]
Ah e acho que já percebi como tornar os algoritmos feitos por mim mais eficazes, em vez de usar um step fixo, fazer um step que altera-se a cada iteracção de acordo com, vá a "distancia" a que está da solução optima. Já vi formulas para fazer isso agora só vai faltar eu arranjar maneiras de aplicar isso  no python :)
