### ISSUE TITLE
speed tests

### ISSUE THREAD

**Issue by j-faria** [jdavidrcamacho/Tests_GP#9]
Como te tinha dito na reunião do outro dia, o tempo para construir as matrizes de covariância devia ser muito parecido ao do george. Tive a olhar para os cálculos que apresentaste e notei duas coisas:
- acho que estavas a incluir o cálculo da likelihood nos tempos, que devia ser separado
- quando calculas a matriz de covariância K, ou seja quando chamas o kernel, era mais eficiente se não usasses loops. Basicamente basta fazer uma coisa do tipo:

```python
class ExpSquared(object):
    def __init__(self, theta, l):
        self.pars = [theta, l]

    def __call__(self, r):
        return self.pars[0]**2 * np.exp(-0.5*r**2/self.pars[1]**2)
```

onde o `r` é calculado assim: `r = x[:, None] - xcalc[None, :]`

Vem cá acima se tiveres dúvidas, mas com isto obtenho 
![speedtests](https://cloud.githubusercontent.com/assets/1958991/20561280/bd2022be-b175-11e6-8e82-37b0e8c3e39f.png)

**Comment by jdavidrcamacho** [comment]
Ok eu cheguei agora ao CAUP assim que puder passo ai em cima para me explicares melhor
